### ISSUE TITLE
1.4.0: Extended ASCII is necessary.

### ISSUE THREAD

**Issue by LeoBitman** [aliascash/alias-wallet-archive#53] opened 2018-06-27 19:47 UTC
Version 1.4.0 I think it have a problem with the accepted character code. 
In Win 10 64. Example: C: \ Users \ "MyUser" \ AppData \ Roaming \ SpectreCoin
If "MyUser" has characters with different accents (ö, é, è, ÿ, ü, ...) 
an error appears and the wallet does not open. In version 1.3.5 this works well.
Instead of using the **ASCII** code the program should use the **Extended ASCII** code.

**Comment by teknex** [comment] 2018-07-31 08:41
Duplicate of https://github.com/spectrecoin/spectre/issues/40

**Comment by shbli** [comment] 2018-07-31 14:46
@teknex I'll take a look soon

**Comment by LeoBitman** [comment] 2018-08-02 02:04
I finished testing version 2.0.4.3 and happily resolves this problem (#53 and also #40).

**Closed as completed** 2018-08-02 02:04 UTC
